<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-06-03 22:51

$extensionPath = t3lib_extMgm::extPath('tt_news');
return array(
	'tx_ttnews' => $extensionPath . 'pi/class.tx_ttnews.php',
	'tx_ttnews_cache' => $extensionPath . 'lib/class.tx_ttnews_cache.php',
	'tx_ttnews_categorytree' => $extensionPath . 'lib/class.tx_ttnews_categorytree.php',
	'tx_ttnews_catmenu' => $extensionPath . 'lib/class.tx_ttnews_catmenu.php',
	'tx_ttnews_cms_layout' => $extensionPath . 'lib/class.tx_ttnews_cms_layout.php',
	'tx_ttnews_compatibility' => $extensionPath . 'class.tx_ttnews_compatibility.php',
	'tx_ttnews_div' => $extensionPath . 'lib/class.tx_ttnews_div.php',
	'tx_ttnews_fetreeview' => $extensionPath . 'lib/class.tx_ttnews_catmenu.php',
	'tx_ttnews_helpers' => $extensionPath . 'lib/class.tx_ttnews_helpers.php',
	'tx_ttnews_itemsprocfunc' => $extensionPath . 'lib/class.tx_ttnews_itemsProcFunc.php',
	'tx_ttnews_module1' => $extensionPath . 'mod1/index.php',
	'tx_ttnews_realurl' => $extensionPath . 'lib/class.tx_ttnews_realurl.php',
	'tx_ttnews_recordlist' => $extensionPath . 'lib/class.tx_ttnews_recordlist.php',
	'tx_ttnews_tcaform_selecttree' => $extensionPath . 'lib/class.tx_ttnews_TCAform_selectTree.php',
	'tx_ttnews_tceforms_categorytree' => $extensionPath . 'lib/class.tx_ttnews_TCAform_selectTree.php',
	'tx_ttnews_tcemain' => $extensionPath . 'lib/class.tx_ttnews_tcemain.php',
	'tx_ttnews_tcemain_cmdmap' => $extensionPath . 'lib/class.tx_ttnews_tcemain.php',
	'tx_ttnews_templateeval' => $extensionPath . 'lib/class.tx_ttnews_templateeval.php',
	'tx_ttnews_tsparserext' => $extensionPath . 'lib/class.tx_ttnews_tsparserext.php',
	'tx_ttnews_typo3ajax' => $extensionPath . 'lib/class.tx_ttnews_typo3ajax.php',
	'tx_ttnews_wizicon' => $extensionPath . 'pi/class.tx_ttnews_wizicon.php',
	'tx_ttnewscatmanager_cm1' => $extensionPath . 'modfunc1/class.tx_ttnewscatmanager_cm1.php',
	'tx_ttnewscatmanager_modfunc1' => $extensionPath . 'modfunc1/class.tx_ttnewscatmanager_modfunc1.php',
	'tx_ttnewscatmanager_treeview' => $extensionPath . 'modfunc1/class.tx_ttnewscatmanager_modfunc1.php',
);
?>