<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_news' => 'News',
		'tt_news.type.I.0' => 'News',
		'tt_news.type.I.1' => 'Article',
		'tt_news.datetime' => 'Date/Time:',
		'tt_news.archivedate' => 'Archive date:',
		'tt_news.related' => 'Related news:',
		'tt_news_cat' => 'News category',
		'tt_news_cat.image' => 'Category image',
		'tt_news.pi_flexform.sheet_general' => 'General Settings',
		'tt_news.pi_flexform.sheet_template' => 'Template',
		'tt_news.pi_flexform.sheet_category' => 'Category Settings',
		'tt_news.pi_flexform.sheet_misc' => 'Other Settings',
		'tt_news.pi_flexform.what_to_display' => 'What to display:',
		'tt_news.pi_flexform.select_deselect_categories' => 'Category mode:',
		'tt_news.pi_flexform.category_selection' => 'Category selection',
		'tt_news.pi_flexform.archive' => 'Archive setting (for LIST)',
		'tt_news.pi_flexform.template_file' => 'Template file',
		'tt_news.pi_flexform.catImageMode' => 'Category Image Link Mode:',
		'tt_news.pi_flexform.catTextMode' => 'Category Text Link Mode:',
		'tt_news.pi_flexform.recursive' => 'Recursive level selection:',
		'tt_news.pi_flexform.catImageMaxWidth' => 'Max width of category image:',
		'tt_news.pi_flexform.catImageMaxHeight' => 'Max height of category image:',
		'tt_news.pi_flexform.maxCatImages' => 'Max number of category images:',
		'tt_news.pi_flexform.maxTextLength' => 'Max length of category text:',
		'tt_news.pi_flexform.maxCatTexts' => 'Max number of categorys texts:',
		'tt_news.pi_flexform.PIDitemDisplay' => 'PageId for single news display:',
		'tt_news.pi_flexform.backPid' => 'PageId to return to:',
		'tt_news.pi_flexform.archive_nonarc' => 'SHOW NON-ARCHIVED',
		'tt_news.pi_flexform.archive_arc' => 'SHOW ARCHIVED',
		'tt_news.pi_flexform.archive_dontcare' => 'Don\'t Care',
		'tt_news.pi_flexform.catLinkMode_TS' => 'Defined by TypoScript',
		'tt_news.pi_flexform.catLinkMode_dontshow' => 'Don\'t display at all',
		'tt_news.pi_flexform.catLinkMode_shownolink' => 'Display, but no links',
		'tt_news.pi_flexform.catLinkMode_catshortcut' => 'Acts as link to category shortcuts',
		'tt_news.pi_flexform.catLinkMode_catsel' => 'Acts as a category selector',
	),
	'dk' => Array (
		'tt_news' => 'Nyheder',
		'tt_news.type.I.0' => 'Nyhed',
		'tt_news.type.I.1' => 'Artikel',
		'tt_news.datetime' => 'Dato/Tidspunkt:',
		'tt_news.archivedate' => 'Arkiv dato:',
		'tt_news.related' => 'Relaterede nyheder:',
		'tt_news_cat' => 'Nyheder kategori',
		'tt_news_cat.image' => 'Kategori Billede',
		'tt_news.pi_flexform.sheet_general' => 'Generelle Indstillinger',
		'tt_news.pi_flexform.sheet_template' => 'Skabelon',
		'tt_news.pi_flexform.sheet_category' => 'Kategori Indstillinger',
		'tt_news.pi_flexform.what_to_display' => 'Hvad der skal vises:',
		'tt_news.pi_flexform.select_deselect_categories' => 'Kategori indstilling',
		'tt_news.pi_flexform.category_selection' => 'Kategori valg',
		'tt_news.pi_flexform.archive' => 'Arkiv indstilling',
		'tt_news.pi_flexform.template_file' => 'Skabelon fil',
		'tt_news.pi_flexform.catImageMode' => 'Kategori Billede Link Indstilling:',
		'tt_news.pi_flexform.catTextMode' => 'Kategori Tekst Link Indstilling:',
		'tt_news.pi_flexform.recursive' => 'Rekursiv niveau valg:',
		'tt_news.pi_flexform.maxCatImages' => 'Max antal kategori billeder:',
		'tt_news.pi_flexform.maxTextLength' => 'Max lжngde pе kategori tekst:',
		'tt_news.pi_flexform.maxCatTexts' => 'Max antal kategori tekster:',
		'tt_news.pi_flexform.PIDitemDisplay' => 'SideId til visning af enkel nyhed:',
		'tt_news.pi_flexform.backPid' => 'SideId at vende tilbage til:',
	),
	'de' => Array (
		'tt_news' => 'News',
		'tt_news.type.I.0' => 'News',
		'tt_news.type.I.1' => 'Artikel',
		'tt_news.datetime' => 'Datum/Zeit:',
		'tt_news.archivedate' => 'Archivdatum:',
		'tt_news.related' => 'In Verbindung stehende News:',
		'tt_news_cat' => 'News Kategorie',
		'tt_news_cat.image' => 'Kategoriebild',
		'tt_news.pi_flexform.sheet_general' => 'Allgemeine Einstellungen',
		'tt_news.pi_flexform.sheet_template' => 'Template',
		'tt_news.pi_flexform.sheet_category' => 'Kategorie Einstellungen',
		'tt_news.pi_flexform.what_to_display' => 'Ansicht:',
		'tt_news.pi_flexform.select_deselect_categories' => 'Kategoriemodus:',
		'tt_news.pi_flexform.category_selection' => 'Kategorieauswahl:',
		'tt_news.pi_flexform.archive' => 'Archiveinstellungen (fьr LIST Ansicht):',
		'tt_news.pi_flexform.template_file' => 'Template Datei',
		'tt_news.pi_flexform.catImageMode' => 'Kategoriebild Link Mode:',
		'tt_news.pi_flexform.catTextMode' => 'Kategorietext Link Mode:',
		'tt_news.pi_flexform.recursive' => 'Rekursiv:',
		'tt_news.pi_flexform.catImageMaxWidth' => 'Maximale Breite fьr Kategoriebild:',
		'tt_news.pi_flexform.catImageMaxHeight' => 'Maximale Hцhe fьr Kategoriebild:',
		'tt_news.pi_flexform.maxCatImages' => 'Maximale Anzahl fьr Kategoriebilder:',
		'tt_news.pi_flexform.maxTextLength' => 'Maximale Lдnge fьr Kategorietext:',
		'tt_news.pi_flexform.maxCatTexts' => 'Maximale Anzahl fьr Kategorietexte:',
		'tt_news.pi_flexform.PIDitemDisplay' => 'Seite fьr die Single-Anzeige (Newsdetails):',
		'tt_news.pi_flexform.backPid' => 'Seite fьr \'Zurьck\':',
		'tt_news.pi_flexform.archive_nonarc' => 'Nur nicht-archivierte',
		'tt_news.pi_flexform.archive_arc' => 'Nur archivierte',
		'tt_news.pi_flexform.archive_dontcare' => 'Egal',
		'tt_news.pi_flexform.catLinkMode_TS' => 'Definiert durch TypoScript',
		'tt_news.pi_flexform.catLinkMode_dontshow' => 'Nicht anzeigen',
		'tt_news.pi_flexform.catLinkMode_shownolink' => 'Anzeigen aber ohne Link',
		'tt_news.pi_flexform.catLinkMode_catshortcut' => 'Anzeigen und Link zum Kategorie-Shortcut',
		'tt_news.pi_flexform.catLinkMode_catsel' => 'Anzeigen und Link als Kategorieselektor',
	),
	'no' => Array (
		'tt_news' => 'Nyheter',
		'tt_news.type.I.0' => 'Nyhet',
		'tt_news.type.I.1' => 'Artikkel',
		'tt_news.datetime' => 'Dato/tid:',
		'tt_news.archivedate' => 'Arkivdato:',
		'tt_news.related' => 'Relaterte nyheter:',
		'tt_news_cat' => 'Nyhetskategori',
		'tt_news_cat.image' => 'Kategori bilde',
		'tt_news.pi_flexform.sheet_general' => 'Generelle instillinger',
		'tt_news.pi_flexform.sheet_template' => 'Mal',
		'tt_news.pi_flexform.sheet_category' => 'Kategori instillinger',
		'tt_news.pi_flexform.what_to_display' => 'Hva skal vises:',
		'tt_news.pi_flexform.select_deselect_categories' => 'Kategori instilling',
		'tt_news.pi_flexform.category_selection' => 'Kategori valg',
		'tt_news.pi_flexform.archive' => 'Arkiv instilling',
		'tt_news.pi_flexform.template_file' => 'Mal fil',
		'tt_news.pi_flexform.catImageMode' => 'Kategori Bilde Link Instilling:',
		'tt_news.pi_flexform.catTextMode' => 'Kategori Tekst Link Instilling:',
		'tt_news.pi_flexform.recursive' => 'Rekursiv nivе valg:',
		'tt_news.pi_flexform.catImageMaxWidth' => 'Maksimal bredde for kategori bildet:',
		'tt_news.pi_flexform.catImageMaxHeight' => 'Maksimal hшyde for kategori bildet:',
		'tt_news.pi_flexform.maxCatImages' => 'Maks antall kategori bilder:',
		'tt_news.pi_flexform.maxTextLength' => 'Maksimal lengde pе kategori tekst:',
		'tt_news.pi_flexform.maxCatTexts' => 'Maksimalt anntall kategori tekster:',
		'tt_news.pi_flexform.PIDitemDisplay' => 'SideID for visning av en enkel nyhet:',
		'tt_news.pi_flexform.backPid' => 'SideID е gе tilbake til:',
		'tt_news.pi_flexform.archive_nonarc' => 'VIS IKKE ARKIVERTE',
		'tt_news.pi_flexform.archive_arc' => 'VIS ARKIVERTE',
		'tt_news.pi_flexform.archive_dontcare' => 'VIS ALLE',
		'tt_news.pi_flexform.catLinkMode_TS' => 'Definert av TypoScript',
		'tt_news.pi_flexform.catLinkMode_dontshow' => 'Ikke vis i det hele tatt',
		'tt_news.pi_flexform.catLinkMode_shownolink' => 'Vis men uten linker',
		'tt_news.pi_flexform.catLinkMode_catshortcut' => 'Fungerer som link til kategori snarveier',
		'tt_news.pi_flexform.catLinkMode_catsel' => 'Fungerer som en kategori velger',
	),
	'it' => Array (
		'tt_news' => 'News',
		'tt_news.type.I.0' => 'News',
		'tt_news.type.I.1' => 'Articolo',
		'tt_news.datetime' => 'Data/Ora:',
		'tt_news.archivedate' => 'Data archiviazione:',
		'tt_news.related' => 'News correlate:',
		'tt_news_cat' => 'Categoria News',
	),
	'fr' => Array (
		'tt_news' => 'Nouvelles',
		'tt_news.type.I.0' => 'Nouvelles',
		'tt_news.type.I.1' => 'Article',
		'tt_news.datetime' => 'Date/Heure:',
		'tt_news.archivedate' => 'Date d\'archivage:',
		'tt_news.related' => 'Nouvelles en relations:',
		'tt_news_cat' => 'Catйgorie de nouvelles',
	),
	'es' => Array (
		'tt_news' => 'Noticias',
		'tt_news.type.I.0' => 'Noticias',
		'tt_news.type.I.1' => 'Artнculo',
		'tt_news.datetime' => 'Fecha/Hora:',
		'tt_news.archivedate' => 'Fecha de archivo:',
		'tt_news.related' => 'Noticias relacionadas:',
		'tt_news_cat' => 'Categorнas de noticias',
	),
	'nl' => Array (
		'tt_news' => 'Nieuws',
		'tt_news.type.I.0' => 'Nieuws',
		'tt_news.type.I.1' => 'Artikel',
		'tt_news.datetime' => 'Datum/Tijd:',
		'tt_news.archivedate' => 'Archiveringsdatum:',
		'tt_news.related' => 'Gerelateerd nieuws:',
		'tt_news_cat' => 'Nieuwscategorie',
		'tt_news_cat.image' => 'Afbeelding van categorie',
		'tt_news.pi_flexform.sheet_general' => 'Algemene instellingen',
		'tt_news.pi_flexform.sheet_template' => 'Sjabloon',
		'tt_news.pi_flexform.sheet_category' => 'Categorie instellingen',
		'tt_news.pi_flexform.what_to_display' => 'Wat te tonen:',
		'tt_news.pi_flexform.select_deselect_categories' => 'Categorie modus:',
		'tt_news.pi_flexform.category_selection' => 'Categorie selectie',
		'tt_news.pi_flexform.archive' => 'Archief instellingen',
		'tt_news.pi_flexform.template_file' => 'Sjabloon bestand',
		'tt_news.pi_flexform.catImageMode' => 'Categorie Afbeelding Link Modus:',
		'tt_news.pi_flexform.catTextMode' => 'Categorie Tekst Link Modus:',
		'tt_news.pi_flexform.recursive' => 'Recursieve niveau selectie:',
		'tt_news.pi_flexform.catImageMaxWidth' => 'Max breedte van categorie afbeelding:',
		'tt_news.pi_flexform.catImageMaxHeight' => 'Max hoogte van categorie afbeelding:',
		'tt_news.pi_flexform.maxCatImages' => 'Max aantal categorie afbeeldingen:',
		'tt_news.pi_flexform.maxTextLength' => 'Max lengte van categorie tekst:',
		'tt_news.pi_flexform.maxCatTexts' => 'Max aantal categorie teksten:',
		'tt_news.pi_flexform.PIDitemDisplay' => 'PaginaID voor het tonen van Single News (Enkel nieuwsartikel):',
		'tt_news.pi_flexform.backPid' => 'PaginaID om naar terug te gaan:',
	),
	'cz' => Array (
		'tt_news' => 'Zprбvy',
		'tt_news.type.I.0' => 'Zprбvy',
		'tt_news.type.I.1' => 'Иlбnek',
		'tt_news.datetime' => 'Datum/Иas:',
		'tt_news.archivedate' => 'Datum archivace:',
		'tt_news.related' => 'Podobnй zprбvy:',
		'tt_news_cat' => 'Kategorie zprбv',
	),
	'pl' => Array (
		'tt_news' => 'Newsy',
		'tt_news.type.I.0' => 'Newsy',
		'tt_news.type.I.1' => 'Artykuі',
		'tt_news.datetime' => 'Data/czas:',
		'tt_news.archivedate' => 'Data archiwum:',
		'tt_news.related' => 'Newsy zwi±zane:',
		'tt_news_cat' => 'Kategoria newsуw',
	),
	'si' => Array (
		'tt_news' => 'Novice',
		'tt_news.type.I.0' => 'Novica',
		'tt_news.type.I.1' => 'Иlanek',
		'tt_news.datetime' => 'Datum/Ura:',
		'tt_news.archivedate' => 'Arhivski datum:',
		'tt_news.related' => 'Sorodne novice:',
		'tt_news_cat' => 'Kategorija novic',
	),
	'fi' => Array (
		'tt_news' => 'Uutiset',
		'tt_news.type.I.0' => 'Uutiset',
		'tt_news.type.I.1' => 'Artikkeli',
		'tt_news.datetime' => 'Pдivдys/Kello',
		'tt_news.archivedate' => 'Arkisto pдivдys:',
		'tt_news.related' => 'Asiaan liittyviд uutisia:',
		'tt_news_cat' => 'Uutisluokka',
		'tt_news_cat.image' => 'Luokan kuva',
		'tt_news.pi_flexform.sheet_general' => 'Yleiset asetukset',
		'tt_news.pi_flexform.sheet_template' => 'Mallinne',
		'tt_news.pi_flexform.sheet_category' => 'Luokka asetukset',
		'tt_news.pi_flexform.what_to_display' => 'Mitд nдytetдддn',
		'tt_news.pi_flexform.select_deselect_categories' => 'Luokka moodi:',
		'tt_news.pi_flexform.category_selection' => 'Luokan valinta',
		'tt_news.pi_flexform.archive' => 'Arkisto asetukset',
		'tt_news.pi_flexform.template_file' => 'Mallinne tiedosto',
		'tt_news.pi_flexform.catImageMode' => 'Luokan kuvalinkki  moodi',
		'tt_news.pi_flexform.catTextMode' => 'Luokan tekstilinkki  moodi',
		'tt_news.pi_flexform.recursive' => 'Rekursiivisen tason valinta',
		'tt_news.pi_flexform.catImageMaxWidth' => 'Maksimi leveys luokan kuvalle:',
		'tt_news.pi_flexform.catImageMaxHeight' => 'Maksimi korkeus luokan kuvalle:',
		'tt_news.pi_flexform.maxCatImages' => 'Max lukumддrд luokan kuville:',
		'tt_news.pi_flexform.maxTextLength' => 'Max pituus luokan tekstille:',
		'tt_news.pi_flexform.maxCatTexts' => 'Max lukumддrд luokan teksteille:',
		'tt_news.pi_flexform.PIDitemDisplay' => 'SivuID yksittдisen uutisen nдytцlle:',
		'tt_news.pi_flexform.backPid' => 'SivuID paluu sivulle:',
		'tt_news.pi_flexform.archive_nonarc' => 'Nдytд arkistoimattomat',
		'tt_news.pi_flexform.archive_arc' => 'Nдytд arkistoidut',
		'tt_news.pi_flexform.archive_dontcare' => 'Дlд vдlitд',
		'tt_news.pi_flexform.catLinkMode_TS' => 'Mддritelty TypoScriptilla',
		'tt_news.pi_flexform.catLinkMode_dontshow' => 'Дlд nдytд ollenkaan',
		'tt_news.pi_flexform.catLinkMode_shownolink' => 'Nдytд, muttei linkkejд',
		'tt_news.pi_flexform.catLinkMode_catshortcut' => 'Toimii linkkinд luokkien oikoteihin',
		'tt_news.pi_flexform.catLinkMode_catsel' => 'Toimii luokan valitsijana',
	),
	'tr' => Array (
		'tt_news' => 'Haberler',
		'tt_news.type.I.0' => 'Haberler',
		'tt_news.type.I.1' => 'Makale',
		'tt_news.datetime' => 'Tarih/Zaman:',
		'tt_news.archivedate' => 'Arюiv tarihi:',
		'tt_news.related' => 'Эlgili haberler:',
		'tt_news_cat' => 'Haber kategorisi',
	),
	'se' => Array (
		'tt_news' => 'Nyheter',
		'tt_news.type.I.0' => 'Nyheter',
		'tt_news.type.I.1' => 'Artikel',
		'tt_news.datetime' => 'Datum/Tid:',
		'tt_news.archivedate' => 'Arkiveringsdatum:',
		'tt_news.related' => 'Nyheter med samma дmne:',
		'tt_news_cat' => 'Nyhetskategori',
	),
	'pt' => Array (
		'tt_news' => 'Notнcias',
		'tt_news.type.I.0' => 'Notнcias',
		'tt_news.type.I.1' => 'Artigo',
		'tt_news.datetime' => 'Data/Hora:',
		'tt_news.archivedate' => 'Data do arquivo:',
		'tt_news.related' => 'Notнcias relacionadas',
		'tt_news_cat' => 'Categoria de notнcias',
	),
	'ru' => Array (
		'tt_news' => 'Новости',
		'tt_news.type.I.0' => 'Новости',
		'tt_news.type.I.1' => 'Статья',
		'tt_news.datetime' => 'Дата/Время:',
		'tt_news.archivedate' => 'Архивная дата:',
		'tt_news.related' => 'Связанные новости:',
		'tt_news_cat' => 'Категория Новостей',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
		'tt_news' => 'Sprбvy',
		'tt_news.type.I.0' => 'Sprбvy',
		'tt_news.type.I.1' => 'Иlбnok',
		'tt_news.datetime' => 'Dбtum/Иas:',
		'tt_news.archivedate' => 'Dбtum archivбcie:',
		'tt_news.related' => 'Podobnй sprбvy:',
		'tt_news_cat' => 'Kategуria sprбv',
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'tt_news' => 'Novosti',
		'tt_news.type.I.0' => 'Novosti',
		'tt_news.type.I.1' => 'Иlanak',
		'tt_news.datetime' => 'Datum/Vrijeme',
		'tt_news.archivedate' => 'Datum arhiviranja',
		'tt_news.related' => 'Povezane novosti',
		'tt_news_cat' => 'Kategorija novosti',
		'tt_news_cat.image' => 'Slika za kategoriju',
		'tt_news.pi_flexform.sheet_general' => 'Opжenite postavke',
		'tt_news.pi_flexform.sheet_template' => 'Predloћak',
		'tt_news.pi_flexform.sheet_category' => 'Postavke kategorija',
		'tt_news.pi_flexform.what_to_display' => 'Љto prokazati:',
		'tt_news.pi_flexform.select_deselect_categories' => 'Mod kategorije:',
		'tt_news.pi_flexform.category_selection' => 'Odabir kategorija',
		'tt_news.pi_flexform.archive' => 'Postavke arhive (za LIST)',
		'tt_news.pi_flexform.template_file' => 'Datoteka predloљka',
		'tt_news.pi_flexform.catImageMode' => 'Link mod za sliku kategorije:',
		'tt_news.pi_flexform.catTextMode' => 'Link mod za tekst kategorije:',
		'tt_news.pi_flexform.recursive' => 'Rekurzivni odabir razine:',
		'tt_news.pi_flexform.catImageMaxWidth' => 'Max. љirina slike kategorije:',
		'tt_news.pi_flexform.catImageMaxHeight' => 'Max. visina slike kategorije:',
		'tt_news.pi_flexform.maxCatImages' => 'Max. broj slika kategorije:',
		'tt_news.pi_flexform.maxTextLength' => 'Max. duћina teksta kategorije:',
		'tt_news.pi_flexform.maxCatTexts' => 'Maksimalni broj tekstova kategorije:',
		'tt_news.pi_flexform.PIDitemDisplay' => 'ID stranice za prikaz jedne novosti:',
		'tt_news.pi_flexform.backPid' => 'Stranica za povratak:',
		'tt_news.pi_flexform.archive_nonarc' => 'PRIKAЋI NE ARHIVIRANE',
		'tt_news.pi_flexform.archive_arc' => 'PRIKAЋI ARHIVIRANE',
		'tt_news.pi_flexform.archive_dontcare' => 'Nije vaћno',
		'tt_news.pi_flexform.catLinkMode_TS' => 'Odreрeno kroz TypoScript',
		'tt_news.pi_flexform.catLinkMode_dontshow' => 'Ne prikazuj uopжe',
		'tt_news.pi_flexform.catLinkMode_shownolink' => 'Prikaћi, ali bez linkova',
		'tt_news.pi_flexform.catLinkMode_catshortcut' => 'Ponaљa se kao link za kratice do kategorija',
		'tt_news.pi_flexform.catLinkMode_catsel' => 'Ponaљa se kao izbornik kategorija',
	),
	'hu' => Array (
		'tt_news' => 'Hнrek',
		'tt_news.type.I.0' => 'Hнrek',
		'tt_news.type.I.1' => 'Cikk',
		'tt_news.datetime' => 'Dбtum/Idх:',
		'tt_news.archivedate' => 'Archнv dбtum:',
		'tt_news.related' => 'Kapcsolуdу cikkek:',
		'tt_news_cat' => 'Hнrkategуria',
		'tt_news_cat.image' => 'Kategуria kйp',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
);
?>