<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_news' => 'News',
		'tt_news.type.I.0' => 'News',
		'tt_news.type.I.1' => 'Article',
		'tt_news.datetime' => 'Date/Time:',
		'tt_news.archivedate' => 'Archive date:',
		'tt_news.related' => 'Related news:',
		'tt_news_cat' => 'News category',
		'tt_news_cat.image' => 'Category image',
		'tt_news.pi_flexform.sheet_general' => 'General Settings',
		'tt_news.pi_flexform.sheet_template' => 'Template',
		'tt_news.pi_flexform.sheet_category' => 'Category Settings',
		'tt_news.pi_flexform.what_to_display' => 'What to display:',
		'tt_news.pi_flexform.select_deselect_categories' => 'Category mode:',
		'tt_news.pi_flexform.category_selection' => 'Category selection',
		'tt_news.pi_flexform.archive' => 'Archive setting',
		'tt_news.pi_flexform.template_file' => 'Template file',
		'tt_news.pi_flexform.catImageMode' => 'Category Image Link Mode:',
		'tt_news.pi_flexform.catTextMode' => 'Category Text Link Mode:',
		'tt_news.pi_flexform.recursive' => 'Recursive level selection:',
		'tt_news.pi_flexform.catImageMaxWidth' => 'Max width of category image:',
		'tt_news.pi_flexform.catImageMaxHeight' => 'Max height of category image:',
		'tt_news.pi_flexform.maxCatImages' => 'Max number of category images:',
		'tt_news.pi_flexform.maxTextLength' => 'Max length of category text:',
		'tt_news.pi_flexform.maxCatTexts' => 'Max number of categorys texts:',
		'tt_news.pi_flexform.PIDitemDisplay' => 'PageId for single news display:',
		'tt_news.pi_flexform.backPid' => 'PageId to return to:',
	),
	'dk' => Array (
		'tt_news' => 'Nyheder',
		'tt_news.type.I.0' => 'Nyhed',
		'tt_news.type.I.1' => 'Artikel',
		'tt_news.datetime' => 'Dato/Tidspunkt:',
		'tt_news.archivedate' => 'Arkiv dato:',
		'tt_news.related' => 'Relaterede nyheder:',
		'tt_news_cat' => 'Nyheder kategori',
		'tt_news_cat.image' => 'Kategori Billede',
		'tt_news.pi_flexform.sheet_general' => 'Generelle Indstillinger',
		'tt_news.pi_flexform.sheet_template' => 'Skabelon',
		'tt_news.pi_flexform.sheet_category' => 'Kategori Indstillinger',
		'tt_news.pi_flexform.what_to_display' => 'Hvad der skal vises:',
		'tt_news.pi_flexform.select_deselect_categories' => 'Kategori indstilling',
		'tt_news.pi_flexform.category_selection' => 'Kategori valg',
		'tt_news.pi_flexform.archive' => 'Arkiv indstilling',
		'tt_news.pi_flexform.template_file' => 'Skabelon fil',
		'tt_news.pi_flexform.catImageMode' => 'Kategori Billede Link Indstilling:',
		'tt_news.pi_flexform.catTextMode' => 'Kategori Tekst Link Indstilling:',
		'tt_news.pi_flexform.recursive' => 'Rekursiv niveau valg:',
		'tt_news.pi_flexform.catImageMaxWidthMax' => 'Max bredde af kategori billede:',
		'tt_news.pi_flexform.catImageMaxWidthMax' => 'Max hшjde af kategori billede:',
		'tt_news.pi_flexform.maxCatImages' => 'Max antal kategori billeder:',
		'tt_news.pi_flexform.maxTextLength' => 'Max lжngde pе kategori tekst:',
		'tt_news.pi_flexform.maxCatTexts' => 'Max antal kategori tekster:',
		'tt_news.pi_flexform.PIDitemDisplay' => 'SideId til visning af enkel nyhed:',
		'tt_news.pi_flexform.backPid' => 'SideId at vende tilbage til:',
	),
	'de' => Array (
		'tt_news' => 'News',
		'tt_news.type.I.0' => 'News',
		'tt_news.type.I.1' => 'Artikel',
		'tt_news.datetime' => 'Datum/Zeit:',
		'tt_news.archivedate' => 'Archivdatum:',
		'tt_news.related' => 'In Verbindung stehende News:',
		'tt_news_cat' => 'News Kategorie',
		'tt_news_cat.image' => 'Kategorie Bild',
	),
	'no' => Array (
		'tt_news' => 'Nyheter',
		'tt_news.type.I.0' => 'Nyhet',
		'tt_news.type.I.1' => 'Artikkel',
		'tt_news.datetime' => 'Dato/tid:',
		'tt_news.archivedate' => 'Arkivdato:',
		'tt_news.related' => 'Relaterte nyheter:',
		'tt_news_cat' => 'Nyhetskategori',
	),
	'it' => Array (
		'tt_news' => 'News',
		'tt_news.type.I.0' => 'News',
		'tt_news.type.I.1' => 'Articolo',
		'tt_news.datetime' => 'Data/Ora:',
		'tt_news.archivedate' => 'Data archiviazione:',
		'tt_news.related' => 'News in relazione:',
		'tt_news_cat' => 'Categoria News',
	),
	'fr' => Array (
		'tt_news' => 'Nouvelles',
		'tt_news.type.I.0' => 'Nouvelles',
		'tt_news.type.I.1' => 'Article',
		'tt_news.datetime' => 'Date/Heure:',
		'tt_news.archivedate' => 'Date d\'archivage:',
		'tt_news.related' => 'Nouvelles en relations:',
		'tt_news_cat' => 'Catйgorie de nouvelles',
	),
	'es' => Array (
		'tt_news' => 'Noticias',
		'tt_news.type.I.0' => 'Noticias',
		'tt_news.type.I.1' => 'Artнculo',
		'tt_news.datetime' => 'Fecha/Hora:',
		'tt_news.archivedate' => 'Fecha de archivo:',
		'tt_news.related' => 'Noticias relacionadas:',
		'tt_news_cat' => 'Categorнas de noticias',
	),
	'nl' => Array (
		'tt_news' => 'Nieuws',
		'tt_news.type.I.0' => 'Nieuws',
		'tt_news.type.I.1' => 'Artikel',
		'tt_news.datetime' => 'Datum/Tijd:',
		'tt_news.archivedate' => 'Archief datum:',
		'tt_news.related' => 'Gerelateerd nieuws:',
		'tt_news_cat' => 'Nieuws categorie',
	),
	'cz' => Array (
		'tt_news' => 'Zprбvy',
		'tt_news.type.I.0' => 'Zprбvy',
		'tt_news.type.I.1' => 'Иlбnek',
		'tt_news.datetime' => 'Datum/Иas:',
		'tt_news.archivedate' => 'Datum archivace:',
		'tt_news.related' => 'Podobnй zprбvy:',
		'tt_news_cat' => 'Kategorie zprбv',
	),
	'pl' => Array (
		'tt_news' => 'Newsy',
		'tt_news.type.I.0' => 'Newsy',
		'tt_news.type.I.1' => 'Artykuі',
		'tt_news.datetime' => 'Data/czas:',
		'tt_news.archivedate' => 'Data archiwum:',
		'tt_news.related' => 'Newsy zwi±zane:',
		'tt_news_cat' => 'Kategoria newsуw',
	),
	'si' => Array (
		'tt_news' => 'Novice',
		'tt_news.type.I.0' => 'Novica',
		'tt_news.type.I.1' => 'Иlanek',
		'tt_news.datetime' => 'Datum/Ura:',
		'tt_news.archivedate' => 'Arhivski datum:',
		'tt_news.related' => 'Sorodne novice:',
		'tt_news_cat' => 'Kategorija novic',
	),
	'fi' => Array (
		'tt_news' => 'Uutiset',
		'tt_news.type.I.0' => 'Uutiset',
		'tt_news.type.I.1' => 'Artikkeli',
		'tt_news.datetime' => 'Pдivдys/Kello',
		'tt_news.archivedate' => 'Arkisto pдivдys:',
		'tt_news.related' => 'Asiaan liittyviд uutisia:',
		'tt_news_cat' => 'Uutisluokka',
	),
	'tr' => Array (
		'tt_news' => 'Haberler',
		'tt_news.type.I.0' => 'Haberler',
		'tt_news.type.I.1' => 'Makale',
		'tt_news.datetime' => 'Tarih/Zaman:',
		'tt_news.archivedate' => 'Arюiv tarihi:',
		'tt_news.related' => 'Эlgili haberler:',
		'tt_news_cat' => 'Haber kategorisi',
	),
	'se' => Array (
	),
	'pt' => Array (
		'tt_news' => 'Notнcias',
		'tt_news.type.I.0' => 'Notнcias',
		'tt_news.type.I.1' => 'Artigo',
		'tt_news.datetime' => 'Data/Hora:',
		'tt_news.archivedate' => 'Data do arquivo:',
		'tt_news.related' => 'Notнcias relacionadas',
		'tt_news_cat' => 'Categoria de notнcias',
	),
	'ru' => Array (
		'tt_news' => 'Новости',
		'tt_news.type.I.0' => 'Новости',
		'tt_news.type.I.1' => 'Статья',
		'tt_news.datetime' => 'Дата/Время:',
		'tt_news.archivedate' => 'Архивная дата:',
		'tt_news.related' => 'Связанные новости:',
		'tt_news_cat' => 'Категория Новостей',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
);
?>