<?php
/**
 * Language labels for plugin 'tt_news'
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'latestHeader' => 'Breaking News:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Category:',
		'textNewsAge' => 'Age: ',
		'more' => '[more]',
		'preAuthor' => 'By:',
		'backToList' => '<- back to: ',
		'goToArchive' => 'go to Archive ->',
		'archiveHeader' => 'ARCHIVE:',
		'archiveItems' => 'items',
		'archiveEmptyMsg' => 'Sorry, Archive contains no items',
		'noResultsMsg' => 'nothing found',
		'searchEmptyMsg' => 'Please enter a searchword.',
		'noNewsToListMsg' => 'no news in this list.',
		'textRelated' => 'Related News:',
		'textLinks' => 'Links:',
		'textFiles' => 'Files:',
		'pi_list_browseresults_prev' => '< Previous',
		'pi_list_browseresults_page' => 'Page ',
		'pi_list_browseresults_next' => 'Next >',
		'noNewsIdMsg' => 'no news_id given',
		'searchButtonLabel' => 'Search',
		'altTextCatSelector' => 'Display only category: ',
		'altTextCatShortcut' => 'Go to: ',
	),
	'dk' => Array (
	),
	'de' => Array (
		'latestHeader' => 'Aktuelles:',
		'textCatLatest' => 'Kat:',
		'textCat' => 'Kategorie:',
		'textNewsAge' => 'Alter:',
		'more' => '[mehr]',
		'preAuthor' => 'Von:',
		'backToList' => '<- Zurück zur Liste',
		'goToArchive' => 'zum Archiv ->',
		'archiveHeader' => 'Nachrichten Archiv:',
		'archiveItems' => 'Einträge',
		'archiveEmptyMsg' => 'Leider keine Einträge im Archiv vorhanden.',
		'noResultsMsg' => 'Keine Ergebnisse',
		'searchEmptyMsg' => 'Bitte geben Sie einen Suchbegriff ein.',
		'noNewsToListMsg' => 'Keine News in dieser Ansicht.',
		'textRelated' => 'In Verbindung stehende News:',
		'textLinks' => 'Links:',
		'textFiles' => 'Dateien:',
		'pi_list_browseresults_prev' => '< zurück',
		'pi_list_browseresults_page' => 'Seite',
		'pi_list_browseresults_next' => 'vor >',
		'noNewsIdMsg' => 'Keine news_id übergeben.',
		'searchButtonLabel' => 'Suchen',
		'altTextCatSelector' => 'Nur diese Kategorie anzeigen:',
		'altTextCatShortcut' => 'Gehe zu:',
	),
	'no' => Array (
		'latestHeader' => 'Siste nytt',
		'textCatLatest' => 'Kat:',
		'textCat' => 'Kategori:',
		'textNewsAge' => 'Alder:',
		'more' => '[les mer]',
		'preAuthor' => 'Av:',
		'backToList' => '<- Tilbake til nyhetsoversikten',
		'goToArchive' => 'gå til Arkiv ->',
		'archiveHeader' => 'ARKIV:',
		'archiveItems' => 'saker',
		'archiveEmptyMsg' => 'Det er ingen saker i arkivet!',
		'noResultsMsg' => 'ingenting funnet',
		'searchEmptyMsg' => 'Vennligst angi et søkeord.',
		'noNewsToListMsg' => 'ingen nyheter i denne listen.',
		'textRelated' => 'relaterte Nyheter:',
		'textLinks' => 'Linker:',
		'textFiles' => 'Filer:',
		'pi_list_browseresults_prev' => '< Forrige',
		'pi_list_browseresults_page' => 'Side',
		'pi_list_browseresults_next' => 'Neste >',
		'noNewsIdMsg' => 'ingen nyhets_ID angitt',
		'searchButtonLabel' => 'Søk',
		'altTextCatSelector' => 'Vis kun kategori:',
		'altTextCatShortcut' => 'Gå til:',
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
		'latestHeader' => 'Últimas noticias:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Categoría:',
		'textNewsAge' => 'Antiguedad:',
		'more' => '[Leer más]',
		'preAuthor' => 'Por:',
		'backToList' => '<- Atrás, a la lista de noticias',
		'goToArchive' => 'ir al Archivo ->',
		'archiveHeader' => 'ARCHIVO:',
		'archiveItems' => 'items',
		'archiveEmptyMsg' => 'Lo sentimos, Archivo no contiene items',
		'noResultsMsg' => 'no se ha encontrado nada',
		'searchEmptyMsg' => 'Nada encontrado',
		'textRelated' => 'Noticias relacionadas:',
		'textLinks' => 'Enlaces:',
		'textFiles' => 'Ficheros:',
		'pi_list_browseresults_prev' => '< Anterior',
		'pi_list_browseresults_page' => 'Página',
		'pi_list_browseresults_next' => 'Siguiente >',
		'noNewsIdMsg' => 'No hay news_id',
		'searchButtonLabel' => 'Buscar',
		'altTextCatSelector' => 'Mostrar sólo categoría:',
		'altTextCatShortcut' => 'Ir a:',
	),
	'nl' => Array (
		'latestHeader' => 'Laatste Nieuws:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Categorie:',
		'textNewsAge' => 'Leeftijd:',
		'more' => '[meer...]',
		'preAuthor' => 'Door:',
		'backToList' => 'nieuwslijst',
		'goToArchive' => 'archief',
		'archiveHeader' => 'ARCHIEF:',
		'archiveItems' => 'items',
		'archiveEmptyMsg' => 'Sorry, Archief bevat geen items',
		'noResultsMsg' => 'niets gevonden',
		'searchEmptyMsg' => 'Vul een zoekterm in.',
		'textRelated' => 'Gerelateerd nieuws',
		'textLinks' => 'Links:',
		'pi_list_browseresults_prev' => '< Vorige',
		'pi_list_browseresults_page' => 'P',
		'pi_list_browseresults_next' => 'Volgende',
		'noNewsIdMsg' => 'geen news_id ingevoerd',
		'searchButtonLabel' => 'Zoek',
		'altTextCatSelector' => 'Toon één categorie',
		'altTextCatShortcut' => 'Ga naar:',
	),
	'cz' => Array (
		'latestHeader' => 'Poslední novinky:',
		'textCatLatest' => 'Kat.:',
		'textCat' => 'Kategorie:',
		'textNewsAge' => 'Ve(k: ',
		'more' => '[více]',
		'preAuthor' => 'Autor:',
		'backToList' => '<- zpe(t: ',
		'goToArchive' => 'jdi do archivu ->',
		'archiveHeader' => 'ARCHÍV:',
		'archiveItems' => 'položky',
		'archiveEmptyMsg' => 'Omlouváme se, archiv neobsahuje žádné položky',
		'noResultsMsg' => 'Nebylo nic nalezeno.',
		'searchEmptyMsg' => 'Vložte hledané slovo.',
		'noNewsToListMsg' => 'V tomto listu nejsou žádné novinky.',
		'textRelated' => 'Pr(íbuzné novinky:',
		'textLinks' => 'Odkazy:',
		'textFiles' => 'Složky:',
		'pi_list_browseresults_prev' => '< Pr(edchozí',
		'pi_list_browseresults_page' => 'Stránka ',
		'pi_list_browseresults_next' => 'Následující >',
		'noNewsIdMsg' => 'Chybí atribut news_id.',
		'searchButtonLabel' => 'Hledat',
		'altTextCatSelector' => 'Zobrazit pouze kategorii: ',
		'altTextCatShortcut' => 'Jdi na: ',
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'latestHeader' => 'Viimeisimmät uutiset:',
		'textCatLatest' => 'Luokka:',
		'textCat' => 'Luokka:',
		'textNewsAge' => 'Ikä',
		'more' => '[lisää]',
		'preAuthor' => 'kirjoittanut:',
		'backToList' => '<- takaisin uutislistalle',
		'goToArchive' => 'siirry arkistoon ->',
		'archiveHeader' => 'Arkisto:',
		'archiveItems' => 'uutiset',
		'archiveEmptyMsg' => 'Valitan, arkistossa ei ole uutisia',
		'noResultsMsg' => 'mitään ei löydetty',
		'searchEmptyMsg' => 'Anna hakusana',
		'noNewsToListMsg' => 'ei uutisia tässä listassa.',
		'textRelated' => 'samankaltaisia uutisia:',
		'textLinks' => 'Linkit:',
		'textFiles' => 'Tiedostot:',
		'pi_list_browseresults_prev' => '< Edellinen',
		'pi_list_browseresults_page' => 'Sivu',
		'pi_list_browseresults_next' => 'Seuraava >',
		'noNewsIdMsg' => 'no news_id given',
		'searchButtonLabel' => 'Etsi',
		'altTextCatSelector' => 'Näytä ainoastaan luokka',
		'altTextCatShortcut' => 'Siirry:',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'latestHeader' => 'Zadnje novosti',
		'textCatLatest' => 'Kat:',
		'textCat' => 'Kategorija:',
		'textNewsAge' => 'Starost:',
		'more' => '[više]',
		'preAuthor' => 'Autor:',
		'backToList' => '<- povratak na popis novosti',
		'goToArchive' => 'u arhivu ->',
		'archiveHeader' => 'ARHIVA',
		'archiveItems' => 'elementi',
		'archiveEmptyMsg' => 'Arhiva je nažalost prazna',
		'noResultsMsg' => 'ništa nije pronaðeno',
		'searchEmptyMsg' => 'Molimo unesite traženu rijeè.',
		'noNewsToListMsg' => 'nema novosti u popisu.',
		'textRelated' => 'povezane novosti',
		'textLinks' => 'Linkovi:',
		'textFiles' => 'Datoteke:',
		'pi_list_browseresults_prev' => '< Prethodna',
		'pi_list_browseresults_page' => 'Stranica',
		'pi_list_browseresults_next' => 'Sljedeæa >',
		'noNewsIdMsg' => 'nije zadan ID novosti',
		'searchButtonLabel' => 'Traži',
		'altTextCatSelector' => 'Prikaži samo kategoriju:',
		'altTextCatShortcut' => 'Idi na:',
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
);
?>