<?php
/**
 * Language labels for plugin 'tt_news'
 * 
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'latestHeader' => 'Breaking News:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Category:',
		'textNewsAge' => 'Age: ',
		'more' => '[more]',
		'preAuthor' => 'By:',
		'backToList' => '&lt;- back to the news List',
		'goToArchive' => 'go to Archive -&gt;',
		'archiveHeader' => 'ARCHIVE:',
		'archiveItems' => 'items',
		'archiveEmptyMsg' => 'Sorry, Archive contains no items',
		'noResultsMsg' => 'nothing found',
		'searchEmptyMsg' => 'Please enter a searchword.',
		'noNewsToListMsg' => 'no news in this list.',
		'textRelated' => 'Related News:',
		'textLinks' => 'Links:',
		'textFiles' => 'Files:',
		'pbrLinkPrev' => '&lt; Previous',
		'pbrPage' => 'Page ',
		'pbrLinkNext' => 'Next &gt;',
		'noNewsIdMsg' => 'no news_id given',
		'searchButtonLabel' => 'Search',
		'altTextCatSelector' => 'Display only category: ',
		'altTextCatShortcut' => 'Go to: ',
	),
	'dk' => Array (
	),
	'de' => Array (
		'latestHeader' => 'Aktuelles:',
		'textCatLatest' => 'Kat:',
		'textCat' => 'Kategorie:',
		'textNewsAge' => 'Alter: ',
		'more' => '[mehr]',
		'preAuthor' => 'Von:',
		'backToList' => '&lt;- zurück zur Liste',
		'goToArchive' => 'zum Archiv -&gt;',
		'archiveHeader' => 'Nachrichten Archiv:',
		'archiveItems' => 'Einträge',
		'archiveEmptyMsg' => 'keine Artikel im Archiv',
		'noResultsMsg' => 'keine Ergebnisse',
		'searchEmptyMsg' => 'Bitte geben Sie einen Suchbegriff ein.',
		'textRelated' => 'verbundene News:',
		'textLinks' => 'Links:',
		'textFiles' => 'Dateien:',
		'pbrLinkPrev' => '&lt; zurück',
		'pbrPage' => 'Seite ',
		'pbrLinkNext' => 'vor &gt;',
		'noNewsIdMsg' => 'keine news_id',
		'searchButtonLabel' => 'Suche',
		'altTextCatSelector' => 'Zeige nur Kategorie: ',
		'altTextCatShortcut' => 'Gehe zu: ',
	),
	'no' => Array (
		'latestHeader' => 'Siste nytt',
		'textCatLatest' => 'Kat:',
		'textCat' => 'Kategori:',
		'textNewsAge' => 'Alder:',
		'more' => '[les mer]',
		'preAuthor' => 'Av:',
		'backToList' => '&lt;- Tilbake til nyhetsoversikten',
		'goToArchive' => 'gå til Arkiv -&gt;',
		'archiveHeader' => 'ARKIV:',
		'archiveItems' => 'saker',
		'archiveEmptyMsg' => 'Det er ingen saker i arkivet!',
		'noResultsMsg' => 'ingenting funnet',
		'searchEmptyMsg' => 'Vennligst angi et søkeord.',
		'textRelated' => 'relaterte Nyheter:',
		'textLinks' => 'Linker:',
		'textFiles' => 'Filer:',
		'pbrLinkPrev' => '&lt; Forrige',
		'pbrPage' => 'Side',
		'pbrLinkNext' => 'Neste &gt;',
		'noNewsIdMsg' => 'ingen nyhets_ID angitt',
		'searchButtonLabel' => 'Søk',
		'altTextCatSelector' => 'Vis kun kategori:',
		'altTextCatShortcut' => 'Gå til:',
	),
	'it' => Array (
	),
	'fr' => Array (
	),
	'es' => Array (
		'latestHeader' => 'Últimas noticias:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Categoría:',
		'textNewsAge' => 'Antiguedad:',
		'more' => '[Leer más]',
		'preAuthor' => 'Por:',
		'backToList' => '<- Atrás, a la lista de noticias',
		'goToArchive' => 'ir al Archivo ->',
		'archiveHeader' => 'ARCHIVO:',
		'archiveItems' => 'items',
		'archiveEmptyMsg' => 'Lo sentimos, Archivo no contiene items',
		'noResultsMsg' => 'no se ha encontrado nada',
		'searchEmptyMsg' => 'Nada encontrado',
		'textRelated' => 'Noticias relacionadas:',
		'textLinks' => 'Enlaces:',
		'textFiles' => 'Ficheros:',
		'pbrLinkPrev' => '< Anterior',
		'pbrPage' => 'Página',
		'pbrLinkNext' => 'Siguiente >',
		'noNewsIdMsg' => 'No hay news_id',
		'searchButtonLabel' => 'Buscar',
		'altTextCatSelector' => 'Mostrar sólo categoría:',
		'altTextCatShortcut' => 'Ir a:',
	),
	'nl' => Array (
		'latestHeader' => 'Laatste Nieuws:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Categorie:',
		'textNewsAge' => 'Leeftijd:',
		'more' => '[meer...]',
		'preAuthor' => 'Door:',
		'backToList' => 'nieuwslijst',
		'goToArchive' => 'archief',
		'archiveHeader' => 'ARCHIEF:',
		'archiveItems' => 'items',
		'archiveEmptyMsg' => 'Sorry, Archief bevat geen items',
		'noResultsMsg' => 'niets gevonden',
		'searchEmptyMsg' => 'Vul een zoekterm in.',
		'textRelated' => 'Gerelateerd nieuws',
		'textLinks' => 'Links:',
		'pbrLinkPrev' => '&lt; Vorige',
		'pbrPage' => 'P',
		'pbrLinkNext' => 'Volgende',
		'noNewsIdMsg' => 'geen news_id ingevoerd',
		'searchButtonLabel' => 'Zoek',
		'altTextCatSelector' => 'Toon één categorie',
		'altTextCatShortcut' => 'Ga naar:',
	),
	'cz' => Array (
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'latestHeader' => 'Viimeisimmät uutiset:',
		'textCatLatest' => 'Luokka:',
		'textCat' => 'Luokka:',
		'textNewsAge' => 'Ikä',
		'more' => '[lisää]',
		'preAuthor' => 'kirjoittanut:',
		'backToList' => '&lt;- takaisin uutislistalle',
		'goToArchive' => 'siirry arkistoon -&gt;',
		'archiveHeader' => 'Arkisto:',
		'archiveItems' => 'uutiset',
		'archiveEmptyMsg' => 'Valitan, arkistossa ei ole uutisia',
		'noResultsMsg' => 'mitään ei löydetty',
		'searchEmptyMsg' => 'Anna hakusana',
		'textRelated' => 'samankaltaisia uutisia:',
		'textLinks' => 'Linkit:',
		'textFiles' => 'Tiedostot:',
		'pbrLinkPrev' => '&lt; Edellinen',
		'pbrPage' => 'Sivu',
		'pbrLinkNext' => 'Seuraava &gt;',
		'noNewsIdMsg' => 'no news_id given',
		'searchButtonLabel' => 'Etsi',
		'altTextCatSelector' => 'Näytä ainoastaan luokka',
		'altTextCatShortcut' => 'Siirry:',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'latestHeader' => 'Zadnje novosti',
		'textCatLatest' => 'Kat:',
		'textCat' => 'Kategorija:',
		'textNewsAge' => 'Starost:',
		'more' => '[više]',
		'preAuthor' => 'Autor:',
		'backToList' => '&lt;- povratak na popis novosti',
		'goToArchive' => 'u arhivu -&gt;',
		'archiveHeader' => 'ARHIVA',
		'archiveItems' => 'elementi',
		'archiveEmptyMsg' => 'Arhiva je nažalost prazna',
		'noResultsMsg' => 'ništa nije pronaðeno',
		'searchEmptyMsg' => 'Molimo unesite traženu rijeè.',
		'textRelated' => 'povezane novosti',
		'textLinks' => 'Linkovi:',
		'textFiles' => 'Datoteke:',
		'pbrLinkPrev' => '&lt; Prethodna',
		'pbrPage' => 'Stranica',
		'pbrLinkNext' => 'Sljedeæa &gt;',
		'noNewsIdMsg' => 'nije zadan ID novosti',
		'searchButtonLabel' => 'Traži',
		'altTextCatSelector' => 'Prikaži samo kategoriju:',
		'altTextCatShortcut' => 'Idi na:',
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
);
?>