<?php
/**
 * Language labels for plugin 'tt_news'
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'latestHeader' => 'Breaking News:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Category:',
		'textNewsAge' => 'Age: ',
		'more' => '[more]',
		'preAuthor' => 'By:',
		'backToList' => '<- Back to: %s',
		'goToArchive' => 'go to Archive ->',
		'archiveHeader' => 'ARCHIVE:',
		'archiveItems' => 'items',
		'archiveEmptyMsg' => 'Sorry, Archive contains no items',
		'noResultsMsg' => 'nothing found',
		'searchEmptyMsg' => 'Please enter a searchword.',
		'noNewsToListMsg' => 'no news in this list.',
		'versionPreviewMessage' => 'Version preview !',
		'versionPreviewMessageLinkToOriginal' => '(click here to see the public version of this record)',
		'nonPlublicVersionMsg' => 'Error! You requested a non-public version of a tt_news article.',
		'noNewsIdMsg' => 'no news_id given',
		'noTranslMsg' => 'Sorry, there is no translation for this news-article.',
		'textRelated' => 'Related News:',
		'textLinks' => 'Links:',
		'textFiles' => 'Files:',
		'textRelatedByCategory' => 'Other news from this category:',
		'pi_list_browseresults_prev' => '< Previous',
		'pi_list_browseresults_page' => 'Page ',
		'pi_list_browseresults_next' => 'Next >',
		'searchButtonLabel' => 'Search',
		'altTextCatSelector' => 'Display only category: ',
		'altTextCatShortcut' => 'Go to: ',
		'catmenuHeader' => 'Select a category:',
	),
	'dk' => Array (
		'latestHeader' => 'Seneste nyt:',
		'textCatLatest' => 'Kat:',
		'textCat' => 'Kategori:',
		'textNewsAge' => 'Alder:',
		'more' => '[mere]',
		'preAuthor' => 'Af:',
		'backToList' => '&lt;- tilbage til nyhedslisten',
		'goToArchive' => 'gå til arkivet -&gt;',
		'archiveHeader' => 'ARKIV:',
		'archiveItems' => 'emne',
		'archiveEmptyMsg' => 'Beklager, Arkivet indeholder ingen emner',
		'noResultsMsg' => 'intet fundet',
		'searchEmptyMsg' => 'Indtast venligst et søgeord.',
		'noNewsToListMsg' => 'ingen nyheder i denne liste',
		'textRelated' => 'Relaterede Nyheder:',
		'textLinks' => 'Links:',
		'textFiles' => 'Filer:',
		'pi_list_browseresults_prev' => '< Forrige',
		'pi_list_browseresults_page' => 'Side',
		'pi_list_browseresults_next' => 'Næste >',
		'noNewsIdMsg' => 'Intet news_id angivet',
		'searchButtonLabel' => 'Søg',
		'altTextCatSelector' => 'Vis kun kategori:',
		'altTextCatShortcut' => 'Gå til:',
	),
	'de' => Array (
		'latestHeader' => 'Aktuelles:',
		'textCatLatest' => 'Kat:',
		'textCat' => 'Kategorie:',
		'textNewsAge' => 'Alter:',
		'more' => '[mehr]',
		'preAuthor' => 'Von:',
		'backToList' => '<- Zurück zu: %s',
		'goToArchive' => 'zum Archiv ->',
		'archiveHeader' => 'Nachrichten Archiv:',
		'archiveItems' => 'Einträge',
		'archiveEmptyMsg' => 'Leider keine Einträge im Archiv vorhanden.',
		'noResultsMsg' => 'Keine Ergebnisse',
		'searchEmptyMsg' => 'Bitte geben Sie einen Suchbegriff ein.',
		'noNewsToListMsg' => 'Keine News in dieser Ansicht.',
		'textRelated' => 'In Verbindung stehende News:',
		'textLinks' => 'Links:',
		'textFiles' => 'Dateien:',
		'pi_list_browseresults_prev' => '< zurück',
		'pi_list_browseresults_page' => 'Seite',
		'pi_list_browseresults_next' => 'vor >',
		'noNewsIdMsg' => 'Keine news_id übergeben.',
		'searchButtonLabel' => 'Suchen',
		'altTextCatSelector' => 'Nur diese Kategorie anzeigen:',
		'altTextCatShortcut' => 'Gehe zu:',
	),
	'no' => Array (
		'latestHeader' => 'Siste nytt',
		'textCatLatest' => 'Kat.:',
		'textCat' => 'Kategori:',
		'textNewsAge' => 'Alder:',
		'more' => '[les mer]',
		'preAuthor' => 'Av:',
		'backToList' => '<- Tilbake til: %s',
		'goToArchive' => 'Til Nyhetsarkivet ->',
		'archiveHeader' => 'NYHETSARKIV:',
		'archiveItems' => 'saker',
		'archiveEmptyMsg' => 'Det er ingen saker i arkivet!',
		'noResultsMsg' => 'ingenting funnet',
		'searchEmptyMsg' => 'Vennligst angi et søkeord.',
		'noNewsToListMsg' => 'ingen nyheter i denne listen.',
		'textRelated' => 'Relaterte Nyheter:',
		'textLinks' => 'Linker:',
		'textFiles' => 'Filer:',
		'pi_list_browseresults_prev' => '< Forrige',
		'pi_list_browseresults_page' => 'Side',
		'pi_list_browseresults_next' => 'Neste >',
		'noNewsIdMsg' => 'ingen nyhets_ID ble oppgitt',
		'searchButtonLabel' => 'Søk',
		'altTextCatSelector' => 'Vis kun kategori:',
		'altTextCatShortcut' => 'Gå til:',
	),
	'it' => Array (
		'latestHeader' => 'News:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Categoria:',
		'textNewsAge' => 'Età:',
		'more' => '[leggi]',
		'preAuthor' => 'Autore:',
		'backToList' => '<- Indietro a: %s',
		'goToArchive' => 'Archivio ->',
		'archiveHeader' => 'ARCHIVIO:',
		'archiveItems' => 'elementi',
		'archiveEmptyMsg' => 'Spiacenti: l\'archivio é vuoto',
		'noResultsMsg' => 'Nessun risultato',
		'searchEmptyMsg' => 'Inserire una parola chiave.',
		'noNewsToListMsg' => 'nessuna news in questa lista.',
		'textRelated' => 'News collegate:',
		'textLinks' => 'Links:',
		'textFiles' => 'Files:',
		'pi_list_browseresults_prev' => '< Precedente',
		'pi_list_browseresults_page' => 'Pagina',
		'pi_list_browseresults_next' => 'Prossima >',
		'noNewsIdMsg' => 'nessun news_id',
		'searchButtonLabel' => 'Cerca',
		'altTextCatSelector' => 'Mostra solo categoria:',
		'altTextCatShortcut' => 'Vai a:',
	),
	'fr' => Array (
		'latestHeader' => 'Actualité:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Categorie:',
		'textNewsAge' => 'Il y a: ',
		'more' => '[details]',
		'preAuthor' => 'Auteur :',
		'backToList' => '<- retour: ',
		'goToArchive' => 'voir les archives ->',
		'archiveHeader' => 'ARCHIVES :',
		'archiveItems' => 'articles',
		'archiveEmptyMsg' => 'Désolé, il y a aucun article dans les archives.',
		'noResultsMsg' => 'pas de résultat',
		'searchEmptyMsg' => 'Veuillez entrer un mot-clé',
		'noNewsToListMsg' => 'Pas d\'article dans la liste.',
		'textRelated' => 'Actualités relatives:',
		'textLinks' => 'Liens:',
		'textFiles' => 'Fichiers:',
		'pi_list_browseresults_prev' => '< Précédent',
		'pi_list_browseresults_page' => 'Page ',
		'pi_list_browseresults_next' => 'Suivant >',
		'noNewsIdMsg' => 'aucun news_id n\' a été donné',
		'searchButtonLabel' => 'Chercher',
		'altTextCatSelector' => 'N\'afficher que cette catégorie: ',
		'altTextCatShortcut' => 'Voir: ',
	),
	'es' => Array (
		'latestHeader' => 'Últimas noticias:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Categoría:',
		'textNewsAge' => 'Antiguedad:',
		'more' => '[Leer más]',
		'preAuthor' => 'Por:',
		'backToList' => '<- Atrás, a la lista de noticias',
		'goToArchive' => 'ir al Archivo ->',
		'archiveHeader' => 'ARCHIVO:',
		'archiveItems' => 'items',
		'archiveEmptyMsg' => 'Lo sentimos, Archivo no contiene items',
		'noResultsMsg' => 'no se ha encontrado nada',
		'searchEmptyMsg' => 'Nada encontrado',
		'noNewsToListMsg' => 'No existen noticias en esta lista.',
		'textRelated' => 'Noticias relacionadas:',
		'textLinks' => 'Enlaces:',
		'textFiles' => 'Ficheros:',
		'pi_list_browseresults_prev' => '< Anterior',
		'pi_list_browseresults_page' => 'Página',
		'pi_list_browseresults_next' => 'Siguiente >',
		'noNewsIdMsg' => 'No hay news_id',
		'searchButtonLabel' => 'Buscar',
		'altTextCatSelector' => 'Mostrar sólo categoría:',
		'altTextCatShortcut' => 'Ir a:',
	),
	'nl' => Array (
		'latestHeader' => 'Laatste Nieuws:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Categorie:',
		'textNewsAge' => 'Leeftijd:',
		'more' => '[meer...]',
		'preAuthor' => 'Door:',
		'backToList' => 'nieuwslijst',
		'goToArchive' => 'archief',
		'archiveHeader' => 'ARCHIEF:',
		'archiveItems' => 'items',
		'archiveEmptyMsg' => 'Sorry, Archief bevat geen items',
		'noResultsMsg' => 'niets gevonden',
		'searchEmptyMsg' => 'Vul een zoekterm in.',
		'noNewsToListMsg' => 'Geen nieuws in deze lijst:',
		'textRelated' => 'Gerelateerd nieuws',
		'textLinks' => 'Links:',
		'textFiles' => 'Bestanden:',
		'pi_list_browseresults_prev' => '< Vorige',
		'pi_list_browseresults_page' => 'Pag.',
		'pi_list_browseresults_next' => 'Volgende',
		'noNewsIdMsg' => 'geen news_id ingevoerd',
		'searchButtonLabel' => 'Zoek',
		'altTextCatSelector' => 'Toon één categorie',
		'altTextCatShortcut' => 'Ga naar:',
	),
	'cz' => Array (
		'latestHeader' => 'Poslední novinky:',
		'textCatLatest' => 'Kat.:',
		'textCat' => 'Kategorie:',
		'textNewsAge' => 'Vìk:',
		'more' => '[více]',
		'preAuthor' => 'Autor:',
		'backToList' => '<- zpìt:',
		'goToArchive' => 'jdi do archivu ->',
		'archiveHeader' => 'ARCHÍV:',
		'archiveItems' => 'položky',
		'archiveEmptyMsg' => 'Omlouváme se, archiv neobsahuje žádné položky',
		'noResultsMsg' => 'Nebylo nic nalezeno.',
		'searchEmptyMsg' => 'Vložte hledané slovo.',
		'noNewsToListMsg' => 'V tomto listu nejsou žádné novinky.',
		'textRelated' => 'Pøíbuzné novinky:',
		'textLinks' => 'Odkazy:',
		'textFiles' => 'Složky:',
		'pi_list_browseresults_prev' => '< Pøedchozí',
		'pi_list_browseresults_page' => 'Stránka',
		'pi_list_browseresults_next' => 'Následující >',
		'noNewsIdMsg' => 'Chybí atribut news_id.',
		'searchButtonLabel' => 'Hledat',
		'altTextCatSelector' => 'Zobrazit pouze kategorii:',
		'altTextCatShortcut' => 'Jdi na:',
	),
	'pl' => Array (
	),
	'si' => Array (
	),
	'fi' => Array (
		'latestHeader' => 'Viimeisimmät uutiset:',
		'textCatLatest' => 'Luokka:',
		'textCat' => 'Luokka:',
		'textNewsAge' => 'Ikä',
		'more' => '[lisää]',
		'preAuthor' => 'kirjoittanut:',
		'backToList' => '<- takaisin uutislistalle',
		'goToArchive' => 'siirry arkistoon ->',
		'archiveHeader' => 'Arkisto:',
		'archiveItems' => 'uutiset',
		'archiveEmptyMsg' => 'Valitan, arkistossa ei ole uutisia',
		'noResultsMsg' => 'mitään ei löydetty',
		'searchEmptyMsg' => 'Anna hakusana',
		'noNewsToListMsg' => 'ei uutisia tässä listassa.',
		'textRelated' => 'samankaltaisia uutisia:',
		'textLinks' => 'Linkit:',
		'textFiles' => 'Tiedostot:',
		'pi_list_browseresults_prev' => '< Edellinen',
		'pi_list_browseresults_page' => 'Sivu',
		'pi_list_browseresults_next' => 'Seuraava >',
		'noNewsIdMsg' => 'no news_id given',
		'searchButtonLabel' => 'Etsi',
		'altTextCatSelector' => 'Näytä ainoastaan luokka',
		'altTextCatShortcut' => 'Siirry:',
	),
	'tr' => Array (
		'latestHeader' => 'Flash haber:',
		'textCatLatest' => 'Kat:',
		'textCat' => 'Kategori:',
		'textNewsAge' => 'zaman:',
		'more' => '(daha)',
		'preAuthor' => 'tarafýndan:',
		'backToList' => '<-geriye:',
		'goToArchive' => 'arþive git->',
		'archiveHeader' => 'ARÞÝV:',
		'archiveItems' => 'nesneler',
		'archiveEmptyMsg' => 'üzgünüm, Arþiv nesne içermiyor',
		'noResultsMsg' => 'Hiçbirþey bulunamadý',
		'searchEmptyMsg' => 'Lütfen arayacaðýnýz kelimeyi girin.',
		'noNewsToListMsg' => 'listede haber yok',
		'textRelated' => 'Ýliþkili haberler:',
		'textLinks' => 'Linkler:',
		'textFiles' => 'Dosyalar:',
		'pi_list_browseresults_prev' => '< Önceki',
		'pi_list_browseresults_page' => 'Sayfa',
		'pi_list_browseresults_next' => 'Sonraki >',
		'noNewsIdMsg' => 'Verilen news_id yok',
		'searchButtonLabel' => 'Ara',
		'altTextCatSelector' => 'Sadece kategoriyi görüntüle:',
		'altTextCatShortcut' => 'Git:',
	),
	'se' => Array (
		'latestHeader' => 'Senaste nytt',
		'textCatLatest' => 'Kat:',
		'textCat' => 'Kategori:',
		'textNewsAge' => 'Ålder:',
		'more' => '[läs mer]',
		'preAuthor' => 'Av:',
		'backToList' => '<- Tillbaka till: %s',
		'goToArchive' => 'gå till arkivet ->',
		'archiveHeader' => 'ARKIV:',
		'archiveItems' => 'artiklar',
		'archiveEmptyMsg' => 'Beklagar, arkivet är tomt',
		'noResultsMsg' => 'inget hittades',
		'searchEmptyMsg' => 'Fyll i ett sökord.',
		'noNewsToListMsg' => 'inga nyheter i denhär listan.',
		'textRelated' => 'Relaterade nyheter:',
		'textLinks' => 'Länkar:',
		'textFiles' => 'Filer:',
		'pi_list_browseresults_prev' => '< Föregående',
		'pi_list_browseresults_page' => 'Denna sida',
		'pi_list_browseresults_next' => 'Nästa >',
		'noNewsIdMsg' => 'inget nyhets_id har givits',
		'searchButtonLabel' => 'Sök',
		'altTextCatSelector' => 'Visa endast kategori:',
		'altTextCatShortcut' => 'Gå till:',
	),
	'pt' => Array (
	),
	'ru' => Array (
		'latestHeader' => 'Ãîðÿ÷èå íîâîñòè:',
		'textCatLatest' => 'Êàò.:',
		'textCat' => 'Êàòåãîðèÿ:',
		'textNewsAge' => 'Äàâíîñòü:',
		'more' => '[ïîäðîáíåå]',
		'preAuthor' => 'Àâòîð:',
		'backToList' => '<- íàçàä â: %s',
		'goToArchive' => 'â Àðõèâ ->',
		'archiveHeader' => 'ÀÐÕÈÂ:',
		'archiveItems' => 'øò.',
		'archiveEmptyMsg' => 'Èçâèíèòå, â àðõèâå íåò çàïèñåé',
		'noResultsMsg' => 'íè÷åãî íå íàéäåíî',
		'searchEmptyMsg' => 'Ïîæàëóéñòà ââåäèòå ñëîâî äëÿ ïîèñêà.',
		'noNewsToListMsg' => 'â ýòîì ñïèñêå íåò íîâîñòåé.',
		'textRelated' => 'Ñâÿçàííûå íîâîñòè:',
		'textLinks' => 'Ññûëêè:',
		'textFiles' => 'Ôàéëû:',
		'pi_list_browseresults_prev' => '< ïðåäûäóù.',
		'pi_list_browseresults_page' => 'Ñòðàíèöà',
		'pi_list_browseresults_next' => 'ñëåäóþù. >',
		'noNewsIdMsg' => 'íåò èäåíòèôèêàòîðà íîâîñòè',
		'searchButtonLabel' => 'Ïîèñê',
		'altTextCatSelector' => 'Ïîêàçàòü òîëüêî êàòåãîðèþ:',
		'altTextCatShortcut' => 'Ïåðåéòè ê:',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'latestHeader' => 'Zadnje novosti',
		'textCatLatest' => 'Kat:',
		'textCat' => 'Kategorija:',
		'textNewsAge' => 'Starost:',
		'more' => '[više]',
		'preAuthor' => 'Autor/ica:',
		'backToList' => '<- povratak na popis novosti',
		'goToArchive' => 'u arhivu ->',
		'archiveHeader' => 'ARHIVA',
		'archiveItems' => 'elementi',
		'archiveEmptyMsg' => 'Arhiva je nažalost prazna',
		'noResultsMsg' => 'ništa nije pronaðeno',
		'searchEmptyMsg' => 'Molimo unesite traženu rijeè.',
		'noNewsToListMsg' => 'nema novosti u popisu.',
		'textRelated' => 'povezane novosti',
		'textLinks' => 'Linkovi:',
		'textFiles' => 'Datoteke:',
		'pi_list_browseresults_prev' => '< Prethodna',
		'pi_list_browseresults_page' => 'Stranica',
		'pi_list_browseresults_next' => 'Sljedeæa >',
		'noNewsIdMsg' => 'nije zadan ID novosti',
		'searchButtonLabel' => 'Traži',
		'altTextCatSelector' => 'Prikaži samo kategoriju:',
		'altTextCatShortcut' => 'Idi na:',
	),
	'hu' => Array (
		'latestHeader' => 'Legújabb híreink',
		'textCatLatest' => 'Kat.:',
		'textCat' => 'Kategória:',
		'textNewsAge' => 'Kor:',
		'more' => '[tovább]',
		'preAuthor' => 'Szerzõ:',
		'backToList' => '<- Vissza: %s',
		'goToArchive' => 'Archivált hírek ->',
		'archiveHeader' => 'Archivált hírek',
		'archiveItems' => 'elemek',
		'archiveEmptyMsg' => 'Nincsenek archivált hírek',
		'noResultsMsg' => 'nincs találat',
		'searchEmptyMsg' => 'Adj meg egy kulcsszót',
		'noNewsToListMsg' => 'nincsenek hírek ebben a listában',
		'textRelated' => 'Kapcsolodó hírek:',
		'textLinks' => 'Hivatkozások:',
		'textFiles' => 'Fájlok:',
		'pi_list_browseresults_prev' => '< Elõzõ',
		'pi_list_browseresults_page' => 'Oldal',
		'pi_list_browseresults_next' => 'Következõ >',
		'noNewsIdMsg' => 'nincs news_id megadva',
		'searchButtonLabel' => 'Keresés',
		'altTextCatSelector' => 'Csak az alábbi kategória:',
		'altTextCatShortcut' => 'Ugrás:',
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'latestHeader' => 'Últimas Notícias:',
		'textCatLatest' => 'Cat:',
		'textCat' => 'Categoria:',
		'textNewsAge' => 'Tempo:',
		'more' => '[mais]',
		'preAuthor' => 'Por:',
		'backToList' => '<- Voltar para: %s',
		'goToArchive' => 'ir para Arquivo ->',
		'archiveHeader' => 'ARQUIVO:',
		'archiveItems' => 'ítens',
		'archiveEmptyMsg' => 'Desculpe, o Arquivo não contém ítens',
		'noResultsMsg' => 'nada encontrado',
		'searchEmptyMsg' => 'Por favor informe a palavra-chave',
		'noNewsToListMsg' => 'sem notícias nesta lista.',
		'textRelated' => 'Notícias Relacionadas:',
		'textLinks' => 'Links:',
		'textFiles' => 'Arquivos:',
		'pi_list_browseresults_prev' => '< Anterior',
		'pi_list_browseresults_page' => 'Página',
		'pi_list_browseresults_next' => 'Próximo >',
		'noNewsIdMsg' => 'nenhum ID de notícia foi informado',
		'searchButtonLabel' => 'Busca',
		'altTextCatSelector' => 'Exibir apenas a categoria:',
		'altTextCatShortcut' => 'Ir para:',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>